spring:    
  profiles:
    active:
    - log_default 
  main:    web-application-type: none
  jackson:   
    property-naming-strategy: SNAKE_CASE
            
logging:
  level:    
    com.example: DEBUG
    
tool:
  multiplicity: 4
  loop: 10

api:
  backend:
    url: http://localhost:8000  
    
    